### ISSUE TITLE
Phx.Live.Metadata released? 

### ISSUE THREAD

**Issue by niccolox** [BartOtten/phoenix_live_head#5]
> This lib is not meant to be used directly. Have a look at `Phx.Live.Favicon`
  > and `Phx.Live.Metadata`. Those libs provide a cleaner syntax and specific
  > documentation for their intended usage.

hey, interested in this ecosystem and especially Phx.Live.Metadata 

I need to upgrade a previous leex implementation I did into Phoenix 1.7 and am looking at your approach

my solution looked like

```
<%= live_html_tag assigns[:website_theme], theme: @website_theme, lang: "en" %>
  <head>
    <%= live_meta_tag assigns[:website_theme], theme: @website_theme, name: "theme" %>
    <%= render(FolkbotWeb.LayoutView, "_meta.app.html", assigns) %>
    <meta name="root_themer" content="true"/>
      <meta name="csrf-token" content={get_csrf_token()} />
    <.live_title suffix=" · Folkbot">
      <%= assigns[:page_title] || @website_rich_title %>
    </.live_title>

    <link phx-track-static rel="stylesheet" href=<%= Routes.static_path(@conn, "/assets/app.css") %> />
    <%= render(FolkbotWeb.LayoutView, "_styles.html", assigns) %>
    <script defer phx-track-static type="text/javascript" src=<%= Routes.static_path(@conn, "/assets/app.js") %>></script>

  </head>
  <body>
   <%= render "_navbar.html", assigns %>
      <%= @inner_content %>
  </body>
</html>

```

**Comment by BartOtten** [comment]
Hi @niccolox,

Due to limited time on my part the Live Metadata lib was never written.

It might be less relevant than expected though, as Search Engines -those who use the data the most- will not be influenced in any way as they won’t navigate using Javascript. As they always will request a non-JS page first (or only), the meta data they use can be ‘hard coded’ like in your example.

There are a few use cases though that still benefit from Live Metadata:
- developer experience: you can navigate a Live application and see how the metadata will look on every page.
- the metadata used by browsers. This requires browsers to respond to changing values (as they do with Favicons). I am not sure if they do (and when they do if it is supported for every meta data).

It should be fairly straightforward to write Live Metadata. Just have a look how Live Favicon uses Live Head; it’s only a thin wrapper. If you want to give it a try, let me know and I’ll talk you though it. 

Otherwise it has to wait till the new version of Phoenix Localized Routes with Verified Routes is released and maybe even longer.

Kind regards,
Bart
